{% set name = "transfocate" %}
{% set version = "0.5.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/transfocate/archive/v{{ version }}.tar.gz
  sha256: 33ad7f0d45a656135e890302079726a1044800c2b57be78b912d5ee4903a59c6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.9
    - bluesky-base
    - databroker
    - matplotlib-base
    - numpy
    - openpyxl
    - ophyd >=1.5.0
    - pandas
    - pcdsdevices >=4.0.0
    - prettytable
    - reportlab

test:
  imports:
    - transfocate

about:
  home: https://github.com/pcdshub/transfocate
  doc_url: https://pcdshub.github.io/transfocate/
  dev_url: https://github.com/pcdshub/transfocate
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: Compound refractive lens (CRL) transfocator device library

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
